server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "GET, POST, DELETE"
            allowed-headers: "*"
      routes:
        - id: mercado
          uri: http://localhost:8082
          filters:
            - StripPrefix=1
          predicates:
            - Path=/mercado/**
        - id: auth
          uri: http://localhost:8090
          filters:
            - StripPrefix=1
          predicates:
            - Path=/auth/**
